# Public Key / Signature Verification Tool (ground tool)
# Verifies ECDSA P-256 signatures generated by the Web API lock system.
# Usage: python -m analyzerex.tools.public_key_verify --public-key pub.pem --data data.json --signature sig.bin
